### Get All Marketing
GET http://localhost:8000/getAllMarketing

### Get All User
GET http://localhost:8000/getAllUser

### Get All Penjualan
GET http://localhost:8000/getAllPenjualan

### Get All Pembayaran
GET http://localhost:8000/getAllPembayaran

### Get All Perhitungan
GET http://localhost:8000/getAllPerhitungan

### Get Marketing Handler
GET http://localhost:8000/getMarketing?name=Alfandy

### Get User Handler
GET http://localhost:8000/getUser?email=nami@gmail.com

### Get Pembayaran Handler
GET http://localhost:8000/getPembayaran?transaction_number=TRX005

### Create Marketing Handler
POST http://localhost:8000/createMarketing
Content-Type: application/json

{ "name": "Alfandy" }

### Create User Handler
POST http://localhost:8000/createUser
Content-Type: application/json

{
    "name": "nami",
    "email": "nami@gmail.com",
    "password": "101010",
    "rekening": [
        {
            "bank": "ovo",
            "saldo": 12000000
        },
        {
            "bank": "bri",
            "saldo": 24000000
        },
        {
            "bank": "bca",
            "saldo": 3600000
        }
    ]
}

### Create Penjualan Handler
POST http://localhost:8000/createPenjualan
Content-Type: application/json

{
    "transaction_number": "TX006",
    "marketing_Id": "648467e7a14d31f7a6427e8f",
    "total_balance": 100000000,
    "tanggal_penjualan": "12/5/2023"
}

### Create Pembayaran Handler Dengan Cara Kontan
POST http://localhost:8000/createPembayaran
Content-Type: application/json

{
    "email": "nami@gmail.com",
    "password": "101010",
    "transaction_number": "TX006",
    "metode_pembayaran": "ovo",
    "jenis_pembayaran": "kontan"
}

### Create Pembayaran Handler Dengan Cara Kredit
POST http://localhost:8000/createPembayaran
Content-Type: application/json

{
    "email": "nami@gmail.com",
    "password": "101010",
    "transaction_number": "TX005",
    "metode_pembayaran": "ovo",
    "jenis_pembayaran": "kredit",
    "jangka_waktu": "3 bulan"
}

### Bayar Tagihan Kredit Pembayaran
GET http://localhost:8000/bayarKredit?transaction_number=TRX005&user_id=64847b2cb1d753a274aca940&tanggal_pembayaran=12/8/2023

### Contoh demonstrasi API via PostMan
https://documenter.getpostman.com/view/21638885/2s93sc4sN4#ae7f6683-b9c8-4607-9e84-4ce9dd255e84